name: Gradle CI/CD

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC daily. Adjust if needed.
  workflow_dispatch:   # Allows manual triggering from the GitHub Actions UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build Shadow JAR
        run: ./gradlew clean shadowJar --build-cache

      - name: Build Docker image
        run: docker build -t bf-schedule-scraper .

      - name: Run Docker container
        run: docker run --rm bf-schedule-scraper
#
#
#
