name: Gradle CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Create Shadow JAR
        run: ./gradlew shadowJar --no-daemon

      - name: Run main class
        run: java -cp build/libs/BF-Schedule-Scraper.jar com.upthink.Bootstrap

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: build/libs/*.jar

      - name: Deploy to staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Add deployment script or commands here
          echo "Deploying to staging environment..."

      - name: Notify deployment status
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Add notification script or commands here
          echo "Deployment to staging completed."

      - name: Clean up
        run: ./gradlew clean --no-daemon
